// Blitz.Web/ClientApp/src/components/ExecutionStatePill.tsx
import { Badge, Tag, ThemeTypings } from '@chakra-ui/react';
import React from 'react';
import { ExecutionState } from '../api';

const colors: Record<ExecutionState, ThemeTypings['colorSchemes']> = {
    failed: 'red',
    finished: 'green',
    timedout: 'yellow',
    started: 'blue',
    triggered: 'cyan',
    pending: 'gray',
    unknown: 'gray',
};

export const ExecutionStatePill: React.FC<{ state?: ExecutionState }> = ({ state = '?' }) => {
    return (
        <Badge size="md" colorScheme={colors[state]}>
            {state.toUpperCase()}
        </Badge>
    );
};

// Blitz.Web/ClientApp/src/components/ExecutionStatePill.vue
﻿<template>
  <b v-if="state"
     class="tag is-light text--smallcaps"
     :class="{'is-danger': failed, 'is-success': finished, 'is-info': triggered}">{{ state }}</b>
  <b v-else class="tag is-light text--smallcaps">Unknown</b>
</template>

<script>
export default {
  name: "ExecutionStatePill",
  props: ['value'],
  data() {
    let state = this.value;
    return {
      state,
      pending: state === 'pending',
      triggered: state === 'triggered',
      started: state === 'started',
      finished: state === 'finished',
      failed: state === 'failed',
    }
  }
}
</script>

<style scoped>
.state {

}
</style>
